apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service 
  labels:
    App: nodeapp
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
    selector:
      App: nodeapp